/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import org.junit.Assume
import spock.lang.Specification

class AssumptionsDemo extends Specification {

    def "should be skipped"() {
        expect:
        Assume.assumeTrue(false)
    }

}
