/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.opentest4j.AssertionFailedError;

class LibraryTest {
    @Test void fail() {
        throw new AssertionFailedError("something went wrong", new NullPointerException());
    }
}
