/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;

import static org.junit.Assert.fail;

public class LibraryTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        fail();
    }
}
