/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;
import java.util.Collections;

import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
public class GradleTestkitCrossJavaVersionPluginFunctionalTest {

    @Test public void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"),
            "plugins { id('org.example.greeting') }");

        String javaHome = System.getProperty("test.java.home");
        assertNotNull("javaHome must not be null", javaHome);
        writeString(new File(projectDir, "gradle.properties"), "\norg.gradle.java.home=" + javaHome + "\n");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.withGradleVersion("5.4.1");
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("throwException");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.buildAndFail();

        // Verify the result
        String output = result.getOutput();
        assertTrue(output.contains("Execution failed for task ':throwException'"));
        assertTrue(output.contains("1.8"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
