/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.junit.jupiter.api.Assertions.*;

@Testcontainers
@SuppressWarnings("resource")
class ContainerTest {

    @Container
    private static final PostgreSQLContainer<?> postgresqlContainer =
            new PostgreSQLContainer<>("postgres:9.6.12")
                    .withDatabaseName("foo")
                    .withUsername("foo")
                    .withPassword("secret");

    @Test
    void a() throws Exception {
        Thread.sleep(1_000);
        assertNotNull(postgresqlContainer.getJdbcUrl());
    }

    @Test
    void b() throws Exception {
        Thread.sleep(2_000);
        fail();
    }
}
