/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import mockit.Mocked;
import org.testng.annotations.Test;

import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.fail;

public class SampleTest {

    @Mocked
    Collaborator mock;

    @Test
    public void test() {
        assertNotNull(mock);
        fail("on purpose");
    }

    interface Collaborator {}
}
