/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;

class ThreadLeakingTest {

    @Test
    void leakThread() {
        Runnable runnable = () -> {
            while (!Thread.interrupted()) {
                System.out.println("Thread " + Thread.currentThread().getName() + " is running");
                try {
                    Thread.sleep(1_000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        var thread = new Thread(null, runnable, "leaked-thread");
        thread.setDaemon(false);
        thread.start();
    }
}
