/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.testng.Assert;
import org.testng.annotations.*;

public class SomeTest {

    @BeforeClass
    public static void beforeClass() {
        Assert.fail();
    }

    @BeforeMethod
    public static void beforeMethod() {
        throw new ClassCastException("exception");
    }

    @Test
    public void test() {
    }
}
