/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.testng.Assert;
import org.testng.annotations.*;

import static org.testng.Assert.*;

public class SomeTest {
    @BeforeClass
    public static void beforeClass() {
        Assert.fail();
    }

    @Test
    public void test() {
    }
}
