/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class LocalDataProviderTest {

    @DataProvider(name = "test1")
    public Object[][] createData1() {
        return new Object[][]{
                {"Cedric", 36},
                {"Anne", 37},
        };
    }

    @Test(dataProvider = "test1")
    public void verifyData1(String n1, Integer n2) {
        System.out.println(n1 + " " + n2);
    }
}
